import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

export const MAX_AVATAR_BYTES = 5 * 1024 * 1024;

const allowedTypes = new Set(["image/png", "image/jpeg", "image/webp", "image/gif"]);

export class UploadError extends Error {}

/**
 * Profile photos are written into `public/uploads/avatars/<userId>/`, which
 * Next serves as ordinary static files. The app runs on one machine and keeps
 * its database there too, so putting the images beside it keeps the whole state
 * of the app in two places you can point at: one Postgres database and one
 * folder. The folder is gitignored — uploads are data, not source.
 */
const AVATAR_ROOT = path.join(process.cwd(), "public", "uploads", "avatars");

/**
 * Whether this process can write to `public/uploads` at all.
 *
 * On Vercel the deployment filesystem is read-only, and the one writable
 * directory is wiped between invocations — so an upload there would either
 * throw EROFS or, worse, appear to succeed and leave a profile pointing at a
 * photo that no longer exists. Both are caught here so the profile form can say
 * something true instead of returning a 500. Every photo already in the
 * directory is a committed file under `public/people`, so the deployed site
 * still shows faces; it just cannot take new ones.
 */
function uploadsAreWritable(): boolean {
  return !process.env.VERCEL;
}

/** The URL prefix that `AVATAR_ROOT` is served under. */
const AVATAR_URL_BASE = "/uploads/avatars";

function extensionFor(type: string): string {
  switch (type) {
    case "image/png":
      return "png";
    case "image/webp":
      return "webp";
    case "image/gif":
      return "gif";
    default:
      return "jpg";
  }
}

/**
 * User ids are generated by this app, so they are already UUIDs — but this is
 * the value that becomes a filesystem path, and a path built from a database
 * field is worth checking. Rejecting anything outside the UUID alphabet makes
 * `../` traversal impossible by construction.
 */
function safeUserDir(userId: string): string {
  if (!/^[A-Za-z0-9_-]+$/.test(userId)) {
    throw new UploadError("Invalid user id.");
  }

  return path.join(AVATAR_ROOT, userId);
}

/**
 * Stores a profile photo and returns the URL it is served at.
 *
 * The filename includes a timestamp so a replacement never collides with a
 * cached copy of the previous one: reusing the name would leave the browser
 * showing the old image.
 */
export async function uploadAvatar(userId: string, file: File): Promise<string> {
  if (!uploadsAreWritable()) {
    throw new UploadError(
      "Profile photos can only be changed on the machine that hosts the app. Everything else on this form still saves.",
    );
  }

  if (file.size === 0) {
    throw new UploadError("That file is empty.");
  }

  if (file.size > MAX_AVATAR_BYTES) {
    throw new UploadError("Profile photos must be 5MB or smaller.");
  }

  if (!allowedTypes.has(file.type)) {
    throw new UploadError("Profile photos must be a PNG, JPEG, WebP, or GIF image.");
  }

  const dir = safeUserDir(userId);
  const name = `${Date.now()}.${extensionFor(file.type)}`;

  try {
    await mkdir(dir, { recursive: true });
    await writeFile(path.join(dir, name), Buffer.from(await file.arrayBuffer()));
  } catch (error) {
    throw new UploadError(
      `Could not save that image: ${error instanceof Error ? error.message : "unknown error"}`,
    );
  }

  return `${AVATAR_URL_BASE}/${userId}/${name}`;
}

/** Removes every stored avatar for a user, used when they clear their photo. */
export async function removeAvatars(userId: string): Promise<void> {
  // Nothing was ever written here, so there is nothing to delete. Returning
  // quietly keeps "clear my photo" working on the deployed site: the column is
  // still cleared, which is the part the visitor asked for.
  if (!uploadsAreWritable()) {
    return;
  }

  const dir = safeUserDir(userId);

  // Missing directory is the normal case for someone who never uploaded one.
  const entries = await readdir(dir).catch(() => [] as string[]);

  await Promise.all(entries.map((entry) => rm(path.join(dir, entry), { force: true })));
}
